apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy304
  labels:
    app: autodeploy304
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717450742720
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy304
  template:
    metadata:
      labels:
        app: autodeploy304
    spec:
      containers:
        - name: autodeploy304
          image: acrworkflow1717450742720.azurecr.io/image-workflow-1717450742720:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
