apiVersion: v1
kind: Service
metadata:
  name: autodeploy304
  namespace: namespace-workflow-1717450742720
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy304
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000